using System.Security.Cryptography;
using System.Text;

namespace ModelsAndMonsters.Rulebook;

/// <summary>
/// One small, self-contained, versioned rule card — the abstract rules for a single action, moved out of the
/// Dungeon Master's system prompt so the DM prompt can stay a compact constitution.
/// </summary>
/// <remarks>
/// A card describes an action <em>in the abstract</em>: what it is, how the intent is recognised, the bindings
/// it needs, its preconditions, its turn cost, its RNG requirement, its visibility, and what it does on
/// success and failure. It carries no live encounter state, no character, no hidden knowledge and no RNG
/// outcome — it is the kind of thing a real rulebook would say, independent of any particular fight. The
/// <see cref="Version"/> is a content hash so a card is independently versionable and any edit changes its
/// version (which in turn invalidates cached guidance that cited the old version).
/// </remarks>
public sealed record RuleCard
{
    /// <summary>
    /// The <see cref="ActionName"/> of a card that governs no action at all — a mechanic every action is
    /// resolved under, such as morale. Such a card is never a candidate action; it is context a resolver may
    /// cite alongside the action card it actually chose.
    /// </summary>
    public const string ReferenceAction = "(reference)";

    /// <summary>Stable rule id, e.g. "inventory.steal" or "combat.attack".</summary>
    public required string RuleId { get; init; }

    /// <summary>
    /// The engine action this card governs (a Dungeon Master tool name), "reject_action" for the generic
    /// refusal card, or <see cref="ReferenceAction"/> for a card that describes a mechanic rather than an act.
    /// </summary>
    public required string ActionName { get; init; }

    /// <summary>True when this card describes a mechanic rather than an action that can be chosen.</summary>
    public bool IsReference => string.Equals(ActionName, ReferenceAction, StringComparison.Ordinal);

    /// <summary>A concise description of what the action is. This is what the resolver reads to recognise the intent — there are no keyword tags routing to the card.</summary>
    public required string Description { get; init; }

    /// <summary>
    /// A one-line summary for the compact index a selection strategy may present instead of the whole book.
    /// </summary>
    /// <remarks>
    /// Written by hand beside the card and never derived from <see cref="Description"/>: a summary generated
    /// by clipping prose would drift silently as the description was edited, and a summary generated by a
    /// model would be one more thing to validate. It is deliberately a SUMMARY, not a keyword list — the
    /// point of the index is that a model reads meaning, exactly as it does with the full card.
    /// </remarks>
    public required string Summary { get; init; }

    /// <summary>
    /// Other rules a decision under this one usually also needs. Declared links, not inferred ones.
    /// </summary>
    /// <remarks>
    /// A selection strategy that retrieves a small set must expand it through these, or it will confidently
    /// hand back the one card an intent looked like and drop the card the decision actually turned on —
    /// escaping without the rule about opening the door first, a threat without the rule about what fear
    /// does and does not compel. Links are one-directional as declared; the expansion follows them once.
    /// </remarks>
    public IReadOnlyList<string> RelatedRuleIds { get; init; } = [];

    /// <summary>The bindings the Dungeon Master must fill from authoritative state to submit the action.</summary>
    public required IReadOnlyList<string> RequiredBindings { get; init; }

    /// <summary>The abstract preconditions that must hold (checked authoritatively by the engine, not the resolver).</summary>
    public required IReadOnlyList<string> Preconditions { get; init; }

    /// <summary>Whether the action consumes the actor's turn.</summary>
    public required string TurnCost { get; init; }

    /// <summary>The randomness the action requires, if any.</summary>
    public required string RngRequirement { get; init; }

    /// <summary>Who learns what when the action resolves.</summary>
    public required string Visibility { get; init; }

    /// <summary>What happens on success.</summary>
    public required string SuccessBehaviour { get; init; }

    /// <summary>What happens on failure.</summary>
    public required string FailureBehaviour { get; init; }

    /// <summary>Variants explicitly not supported, so the resolver can recognise and refuse them.</summary>
    public required IReadOnlyList<string> Exclusions { get; init; }

    /// <summary>
    /// A short content hash over every field except the version itself, so a card is independently
    /// versionable and any change to its text yields a new version. Computed on access (not cached in a
    /// field) so that a modified copy made with <c>with</c> reports its new content's version, not the
    /// original's — the cost is a small hash over short text, computed only a handful of times per request.
    /// </summary>
    public string Version => ComputeVersion();

    private string ComputeVersion()
    {
        var builder = new StringBuilder();
        builder.Append(RuleId).Append('\n');
        builder.Append(ActionName).Append('\n');
        builder.Append(Description).Append('\n');
        builder.Append(Summary).Append('\n');
        builder.AppendJoin("|", RelatedRuleIds).Append('\n');
        builder.AppendJoin("|", RequiredBindings).Append('\n');
        builder.AppendJoin("|", Preconditions).Append('\n');
        builder.Append(TurnCost).Append('\n');
        builder.Append(RngRequirement).Append('\n');
        builder.Append(Visibility).Append('\n');
        builder.Append(SuccessBehaviour).Append('\n');
        builder.Append(FailureBehaviour).Append('\n');
        builder.AppendJoin("|", Exclusions);

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(builder.ToString()));
        return "v1-" + Convert.ToHexStringLower(hash)[..8];
    }

    /// <summary>
    /// Renders the card as a compact block for the resolver's request: everything that says what the action
    /// IS and IS NOT, and nothing that says what happens once it has been chosen. Contains no live state.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The absent fields — required bindings, turn cost, RNG, visibility, and the success and failure
    /// behaviours — are deliberate, and they are the majority of the card's text. Since v0.8 the resolver no
    /// longer echoes them back: it answers with an action and a citation, and the consultant fills those
    /// fields from this very card afterwards (<c>RulebookConsultant.Hydrate</c>). Sending them was therefore
    /// asking the model to read ten thousand characters it could not use, on every consultation.
    /// </para>
    /// <para>
    /// That was not merely wasteful. With the whole book at 21 cards the request reached ~8,065 tokens
    /// against an 8,192-token window, leaving about 127 tokens to reply in; a live run truncated 5 of 57
    /// replies mid-JSON, each surfacing as malformed guidance and an in-world refusal of an ordinary action.
    /// What the resolver needs in order to SELECT is what an action is, what it is not, and what must hold
    /// for it — so that is what it is shown.
    /// </para>
    /// </remarks>
    public string ToResolverBlock()
    {
        var builder = new StringBuilder();
        builder.AppendLine(IsReference
            ? $"RULE {RuleId} (version {Version}) — BACKGROUND MECHANIC, not an action anyone can choose"
            : $"RULE {RuleId} (version {Version}) — action: {ActionName}");
        builder.AppendLine($"  what it is: {Description}");
        builder.AppendLine($"  preconditions: {Join(Preconditions)}");
        builder.AppendLine($"  not supported: {Join(Exclusions)}");
        return builder.ToString().TrimEnd();
    }

    /// <summary>
    /// Renders the card as ONE line for a compact index: its id, the action it governs, and its summary.
    /// This is what a selection strategy shows a model in place of the whole card, so that the model still
    /// does the semantic work but reads a few hundred characters instead of a few thousand.
    /// </summary>
    public string ToIndexLine() =>
        IsReference
            ? $"{RuleId} [background mechanic] — {Summary}"
            : $"{RuleId} [{ActionName}] — {Summary}";

    private static string Join(IReadOnlyList<string> values) => values.Count == 0 ? "none" : string.Join("; ", values);
}
